/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_menu (void);
GtkWidget* create_about (void);

void get_current_levels();
void get_mute_state();
void hide_me();

struct originalset
{
  unsigned char mainvol;
  unsigned char pcm;
  unsigned char speaker;
  unsigned char line1;
  unsigned char cd;
  unsigned char mic;
};
